### ISSUE TITLE
Index Error: tuple index out of range

### ISSUE THREAD

**Issue by kinkunchan** [giannisnik/segk#1]
When running the algorithm on some of the graphs, I've encountered such error
```
Traceback (most recent call last):
  File "lib/segk/segk.py", line 108, in <module>
    main()
  File "lib/segk/segk.py", line 103, in main
    embeddings = segk(nodes, edgelist, args.radius, args.dim, args.kernel)

  File "lib/segk/segk.py", line 64, in segk
    Gs.append(Graph(edges, node_labels=node_labels))

  File "/home/ubuntu/RL/env/lib/python3.6/site-packages/grakel/graph.py", line 162, in __init__
    edge_labels)

  File "/home/ubuntu/RL/env/lib/python3.6/site-packages/grakel/graph.py", line 231, in build_graph
    self._import_adjacency(g)

  File "/home/ubuntu/RL/env/lib/python3.6/site-packages/grakel/graph.py", line 940, in _import_adjacency
    if n != adjacency_matrix.shape[1]:

IndexError: tuple index out of range
```

**Comment by giannisnik** [comment]
Hi @kinkunchan . I've never encountered this error so far. I guess it is related to the structure of the graph that you pass on to the algorithm. Can you give me access to the edgelist file you utilized?

**Comment by kinkunchan** [comment]
The error is found: the algorithm doesn't accept graphs that contain **self-loops**.

You can either remove the self-loop in the input edgelist or add a line in the `util.py`

```
# add this line before nodes = set()
edges = [e for e in edges if e[0] != e[1]]
# below is the original file
nodes = set()
```
